### PR TITLE
Create empty RemoteCollection when xml response is blank

### PR DESCRIPTION
**Pull request by klacointe**
Can you take a look at my patch and said if it make sense for you

Thanks !

### CODE REVIEW

**Comment by c42** [comment]
Hi, 

I have merged the code. I am planning to release the new version of gem tomorrow. I'll drop you a note once a new version is out.

Thanks

**Comment by c42** [comment]
Hi,

I have released pox_paginate 0.2.2 with a patch to load empty remote collection in case of blank xml

Thanks for the patch.

**Comment by klacointe** [comment]
Thanks !

**Comment by kaiwren** [comment]
I've added your name to the contributors list in the README - please feel free to update with your real name should you wish to. Thanks for the patch :)

**Pull request closed without merging**
